pub const OP_VERIFY_UNROLLED_RECURSION_LAYER_IN_UNIFIED_CIRCUIT: u32 = 1;
pub const OP_VERIFY_UNIFIED_RECURSION_LAYER_IN_UNIFIED_CIRCUIT: u32 = 2;

pub const OP_VERIFY_BASE_LAYER_IN_UNROLLED_CIRCUITS: u32 = 1;
pub const OP_VERIFY_RECURSIVE_LAYER_IN_UNROLLED_CIRCUITS: u32 = 2;
pub const OP_VERIFY_FULL_MACHINE_BASE_LAYER_IN_UNROLLED_CIRCUITS: u32 = 3;
