set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR riscv32)
set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)

set(RISCV_GCC_TRIPLE "riscv32-unknown-elf" CACHE STRING "RISC-V GCC target triple")
set(
  RISCV_GCC_TOOLCHAIN_ROOT
  ""
  CACHE PATH
  "Optional root directory of the RISC-V GCC toolchain"
)

list(APPEND CMAKE_TRY_COMPILE_PLATFORM_VARIABLES RISCV_GCC_TRIPLE)
list(APPEND CMAKE_TRY_COMPILE_PLATFORM_VARIABLES RISCV_GCC_TOOLCHAIN_ROOT)

if(RISCV_GCC_TOOLCHAIN_ROOT)
  set(RISCV_GCC_BIN_DIR "${RISCV_GCC_TOOLCHAIN_ROOT}/bin")
endif()

if(NOT DEFINED CMAKE_C_COMPILER)
  find_program(
    RISCV_GCC
    NAMES ${RISCV_GCC_TRIPLE}-gcc
    HINTS ${RISCV_GCC_BIN_DIR}
    REQUIRED
  )
  set(CMAKE_C_COMPILER "${RISCV_GCC}" CACHE FILEPATH "" FORCE)
endif()
if(NOT DEFINED CMAKE_CXX_COMPILER)
  find_program(
    RISCV_GXX
    NAMES ${RISCV_GCC_TRIPLE}-g++ ${RISCV_GCC_TRIPLE}-c++
    HINTS ${RISCV_GCC_BIN_DIR}
    REQUIRED
  )
  set(CMAKE_CXX_COMPILER "${RISCV_GXX}" CACHE FILEPATH "" FORCE)
endif()
if(NOT DEFINED CMAKE_ASM_COMPILER)
  set(CMAKE_ASM_COMPILER "${CMAKE_C_COMPILER}" CACHE FILEPATH "" FORCE)
endif()

if(NOT DEFINED CMAKE_OBJCOPY)
  find_program(
    RISCV_OBJCOPY
    NAMES ${RISCV_GCC_TRIPLE}-objcopy
    HINTS ${RISCV_GCC_BIN_DIR}
  )
endif()

if(RISCV_OBJCOPY)
  set(CMAKE_OBJCOPY "${RISCV_OBJCOPY}" CACHE FILEPATH "" FORCE)
endif()

set(COMMON_FLAGS "-march=rv32im_zicsr -mabi=ilp32 -mrelax -mstrict-align")

string(APPEND CMAKE_C_FLAGS_INIT " ${COMMON_FLAGS}")
string(APPEND CMAKE_CXX_FLAGS_INIT " ${COMMON_FLAGS}")
string(APPEND CMAKE_ASM_FLAGS_INIT " ${COMMON_FLAGS}")
