#pragma once

#include "common.cuh"

using namespace ::airbender::witness;

namespace airbender::witness::placeholder {

enum PlaceholderTag : u32 {
  XregsInit,
  XregsFin,
  XregInit,
  XregFin,
  Instruction,
  MemSlot,
  PcInit,
  PcFin,
  StatusInit,
  StatusFin,
  IeInit,
  IeFin,
  IpInit,
  IpFin,
  TvecInit,
  TvecFin,
  ScratchInit,
  ScratchFin,
  EpcInit,
  EpcFin,
  CauseInit,
  CauseFin,
  TvalInit,
  TvalFin,
  ModeInit,
  ModeFin,
  MemorySaptInit,
  MemorySaptFin,
  ContinueExecutionInit,
  ContinueExecutionFin,
  ExternalOracle,
  Trapped,
  InvalidEncoding,
  FirstRegMem,
  SecondRegMem,
  WriteRegMemReadWitness,
  WriteRegMemWriteValue,
  MemoryLoadOp,
  WriteRdReadSetWitness,
  ShuffleRamLazyInitAddressThis,
  ShuffleRamLazyInitAddressNext,
  ShuffleRamAddress,
  ShuffleRamReadTimestamp,
  ShuffleRamReadValue,
  ShuffleRamIsRegisterAccess,
  ShuffleRamWriteValue,
  ExecuteDelegation,
  DelegationType,
  DelegationABIOffset,
  DelegationWriteTimestamp,
  DelegationMemoryReadValue,
  DelegationMemoryReadTimestamp,
  DelegationMemoryWriteValue,
  DelegationRegisterReadValue,
  DelegationRegisterReadTimestamp,
  DelegationRegisterWriteValue,
  DelegationIndirectReadValue,
  DelegationIndirectReadTimestamp,
  DelegationIndirectWriteValue,
  DelegationNondeterminismAccess,
  DelegationNondeterminismAccessNoSplits,
  ExecuteOpcodeFamilyCycle,
  OpcodeFamilyCycleInitialTimestamp,
  OpcodeFamilyCycleFinalTimestamp,
  RS1Index,
  RS2Index,
  MemLoadAddress,
  RDIndex,
  RDIsZero,
  DecodedImm,
  DecodedFunct3,
  DecodedFunct7,
  DecodedExecutorFamilyMask,
  LoadStoreRamValue,
  MemStoreAddress,
  DelegationIndirectAccessVariableOffset,
};

struct Placeholder {
  PlaceholderTag tag;
  u32 payload[2];
};

} // namespace airbender::witness::placeholder