pub const ADD_SUB_LUI_AUIPC_MOP_CIRCUIT_FAMILY_IDX: u8 = 1;
pub const JUMP_BRANCH_SLT_CIRCUIT_FAMILY_IDX: u8 = 2;
pub const SHIFT_BINARY_CIRCUIT_FAMILY_IDX: u8 = 3;
pub const MUL_DIV_CIRCUIT_FAMILY_IDX: u8 = 4;

pub const LOAD_STORE_WORD_ONLY_CIRCUIT_FAMILY_IDX: u8 = 16;
pub const LOAD_STORE_SUBWORD_ONLY_CIRCUIT_FAMILY_IDX: u8 = 17;
pub const LOAD_STORE_CIRCUIT_FAMILY_IDX: u8 = 16;

pub const INITS_AND_TEARDOWNS_FORMAL_CIRCUIT_FAMILY_IDX: u8 = u8::MAX;

pub const REDUCED_MACHINE_CIRCUIT_FAMILY_IDX: u8 = 128;
